import type { Metadata } from 'next'
import '@/styles/globbal.scss'
import React, { ReactNode } from 'react'
import Header from '@/components/Header/Header'
import Footer from '@/components/Footer/Footer'
import s from './page.module.scss'

export const metadata: Metadata = {
  title: 'Uladzislau Ostapuk',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang="en">
      <body className={s.bodyBlock}>
        <Header />
        <main className={s.mainBlock}>{children}</main>
        <Footer />
      </body>
    </html>
  )
}
